### PR TITLE
Use Conda Forge graph for package name mappings and less downloads

### LINKED ISSUE #12: Switch to using cf-graph-countyfair for pypi -> conda forge mapping
I [recently heard about](https://github.com/Quansight/Quansight.github.io/discussions/44#discussioncomment-1254965) the [Grayskull](https://github.com/conda-incubator/grayskull) package, from @ForgottenProgramme, which can automatically generate a Conda forge package from a PyPi package. @jaimergp mentioned that they [use cf-graph-countyfair](https://github.com/regro/cf-graph-countyfair/tree/master/mappings/pypi) to maintain a mapping between PyPi and conda forge package names. Beni could use this to perform its mapping as well, since often the PyPi and conda forge name are different.

### PR DESCRIPTION
**Pull request by flying-sheep**
Fixes #12

However, not everything seems to be in there, e.g. `black` is missing. Maybe the file only contains mappings that are not trivial?

### CODE REVIEW

**Comment by saulshanabrook** [comment]
Oh nice, this is awesome! @jaimergp do you know how to best use this file?

**Comment by flying-sheep** [comment]
I investigated a bit, but I can’t find a simple list of packages available. I *think*:

- `cf-graph-countyfair/master/graph.json` contains all conda packages (and their for us useless dependency info)
- `cf-graph-countyfair/master/mappings/pypi/name_mapping.yaml` contains all combinations of PyPI name, conda name, and import where the three are not equivalent
- `cf-scripts/master/conda_forge_tick/pypi_name_mapping_static.yaml` the same as the one before, but manually maintained. IDK if the info in this one is included in the previous one.

**Comment by jaimergp** [comment]
> * `cf-graph-countyfair/master/mappings/pypi/name_mapping.yaml` contains all combinations of PyPI name, conda name, and import where the three are not equivalent

Yep this is the one you need. It should only contain known packages (to conda-forge) that don't share a name with PyPI. @viniciusdc might have some more info, since he's more involved with the bot infrastructure there.

**Comment by viniciusdc** [comment]
> > * `cf-graph-countyfair/master/mappings/pypi/name_mapping.yaml` contains all combinations of PyPI name, conda name, and import where the three are not equivalent
> 
> Yep this is the one you need. It should only contain known packages (to conda-forge) that don't share a name with PyPI. @viniciusdc might have some more info, since he's more involved with the bot infrastructure there.

Indeed that's the best source for your problem. There is a notebook where you can inspect some of the metadata within the conda-forge json in that repo as well, if needed. About the usage of the static maps, this one  [pypi_mapping.py](https://github.com/regro/cf-scripts/blob/005cb910aadcb52e5f38af7b29f5877950f85b0a/conda_forge_tick/pypi_name_mapping.py#L284) generates the magic

**Comment by flying-sheep** [comment]
Great, thank you!

This is looking good. Would be nice if there was a smaller JSON blob to download for the list of packages on conda forge, but with some caching, the `graph.json` will work too.

**Comment by flying-sheep** [comment]
Using it now looks like this (once an hour, otherwise no progress bars)

```console
$ python -m beni pyproject.toml
Creating cache for name_mapping.yaml at /home/phil/.cache/beni: 100%|█████████████████████████████| 636k/636k [00:00<00:00, 5.46MB/s]
Creating cache for graph.json at /home/phil/.cache/beni: 100%|██████████████████████████████████| 8.28M/8.28M [00:01<00:00, 5.70MB/s]
channels:
- conda-forge
dependencies:
- ...
```

**Comment by saulshanabrook** [comment]
Awesome! That looks great 🎈

**Pull request merged**
